server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poem?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: asdf123456
mybatis:
  mapper-locations: classpath:mapping/*.xml

  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
logging:
  level:
    com.poetry.mapper.*: debug
